services:
  minio:
    image: minio/minio:latest
    container_name: de_healthcare
    ports:
      - "9000:9000"
      - "9002:9002"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9002"
    volumes:
      - ./data:/data
    networks:
      - model_engine_default

networks:
  model_engine_default:
    external: true